version: 2

sources: 
  - name: northwind_etl
    tables:
        - name: orders
        - name: customers
          columns:
            - name: customer_id
        - name: employees
          columns:
            - name: employee_id
        - name: products
          columns:
            - name: products_id
        - name: shippers
          columns:
            - name: shipper_id
        - name: suppliers
          columns:
            - name: suplier_id
        - name: order_details
          columns:
            - name: order_id
